version: "3"

services: 
  prometheus:
    image: prom/prometheus:latest
    user: root
    restart: always
    ports:
      - "9090:9090"
    command: --config.file=/vagrant/prometheus/prometheus.yml
    volumes: 
      - /vagrant/prometheus:/vagrant/prometheus
  
  grafana:
    image: grafana/grafana:latest
    user: root
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /vagrant/grafana:/etc/grafana
      - /vagrant/grafana-db:/var/lib/grafana